---
- name: Installation et configuration d'OpenSSH
  hosts: localhost
  become: yes
  tasks:
    - name: Vérification des droits root
      assert:
        that: ansible_user_id == 'root'
        fail_msg: "Ce playbook doit être exécuté en tant que root."

    - name: Mise à jour des paquets et installation d'OpenSSH Server
      apt:
        update_cache: yes
        name: openssh-server
        state: present

    - name: Configuration de SSH pour utiliser uniquement le protocole SSHv2
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Protocol'
        line: 'Protocol 2'
        state: present

    - name: Création de la bannière SSH
      copy:
        dest: /etc/ssh/banner
        content: |
          ********************************************************
          *                 AVERTISSEMENT                        *
          https://192.168.1.98***********************************************
          *  Cette connexion est la propriété de la société X.   *
          *  L'accès est autorisé uniquement aux utilisateurs    *
          *  autorisés. Toute autre tentative constitue une      *
          *  violation de la sécurité et sera poursuivie en      *
          *  justice.                                            *
          ********************************************************
          ********************************************************
          *                    WARNING                           *
          ********************************************************
          *  This connection is the property of X. Access is     *
          *  only permitted to authorized users. Any other       *
          *  access attempt constitutes a violation of system    *
          *  security and will be prosecuted to the fullest      *
          *  extent of the law.                                  *
          ********************************************************

    - name: Activation de la bannière SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Banner'
        line: 'Banner /etc/ssh/banner'
        state: present

    - name: Vérification de la syntaxe de la configuration SSH
      command: sshd -t
      register: sshd_config_test
      failed_when: sshd_config_test.rc != 0

    - name: Redémarrage du service SSH
      systemd:
        name: sshd
        state: restarted
